version: '3'
services:
  nginx:
    container_name: waywander_nginx
    build: docker/nginx
    ports:
      - '8081:80'
    volumes:
      - './:/var/www/html/'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
  php:
    container_name: waywander_php
    build: docker/php
    volumes:
      - './:/var/www/html/'
      - './docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
      - './docker/php/php.ini:/usr/local/etc/php/php.ini'
